### ISSUE TITLE
Gewzungene Verifikation nicht möglich

### ISSUE THREAD

**Issue by Soulseller33** [xXSchrandXx/de.xxschrandxx.wsc.minecraft-linker#6]
Vorweg:
Ich nutze: [Version 4.0.1](https://www.woltlab.com/pluginstore/download/17791/) vom minecraft linker 
Minecraft API: [Version 4.0.1](https://www.woltlab.com/pluginstore/download/17809/)
und das passende Bridge Plugin.

WoltLab Suite Core Version 6.0.11

Erzwingen der Verfikation trotz gesetztem Haken wird nicht vorgenommen.
Weder bei bereits registrierten Nutzern noch bei einer neu Registrierung.

Auch eine Erzwingung der Verifikation über eine Gruppenbedinung scheint nicht zu funktionieren.

Versuch: Neue Benutzer gruppe erstellt und eine autoamtische Zuordnung erstellt und als Bedinung das derjenige Verifziert ist.
Hier wurden einfach alle User in die neue Gruppe übernommen. Die Bedinung wurde immer komplett ignoriert und es wurde immer true gesetzt.

**Comment by xXSchrandXx** [comment]
Hallo,

das Erzwingen der Verlinkung ist ein noch nicht fertiggestelltes Feature.
Die Gruppenbedingung [user.minecraftLinker.mandatory](https://github.com/xXSchrandXx/de.xxschrandxx.wsc.minecraft-linker/blob/main/userGroupOption.xml#L12) hat noch keine Funktion...
Ich habe vergessen dies in der Beschreibung klarzustellen.
Auch die Aktivierungsmethode ist noch nicht fertiggestellt.

**Comment by Soulseller33** [comment]
Hi ok, danke für die Info.
Gibt es einen Zeitplan wann das final implementiert wird?

Das Plugin selbst ist recht gut, aber ohne den zwang leider kaum nutzbar.

**Comment by xXSchrandXx** [comment]
Hallo,

einen genauen Zeitplan habe ich nicht, denke aber dass ich das relativ schnell hinbekomme.

**Comment by Soulseller33** [comment]
Ok das wäre super, viele dank dir schonmal.

**Comment by xXSchrandXx** [comment]
Die Änderungen wurden von WoltLab akzeptiert.
In meinen Tests hats alles funktioniert. Falls noch Fehler auftreten, gerne wieder ein Issue erstellen.
